---
name: cmpsc-301-Fall-2021-exam2
break: true
indent: 4
---

# --> check the technical writing
src/exam2.r:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact



# --> check the number of commits beyond a threshold
CountCommits --count 3
